#!/usr/bin/env bash

# Get the current pane's working directory from tmux
CURRENT_DIR=$(tmux display-message -p -F "#{pane_current_path}")

# Fallback to $PWD if not running inside tmux
CURRENT_DIR=${CURRENT_DIR:-$PWD}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects ~/media ~/documents ~/downloads ~/.config "$CURRENT_DIR" -mindepth 1 -maxdepth 2 -type d -not -name ".*" 2>/dev/null | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
